name: AI (Python) Deployment to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - 'ai/**' # ◀ ai 폴더 내부의 코드가 변경되었을 때만 이 파이프라인 작동

jobs:
  deploy-ai:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. AI 소스 코드들만 EC2의 recommend_lambda 경로로 전송
      - name: Copy Python files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "ai/*" # ◀ ai 폴더 하위의 모든 자원 대상
          target: "/home/ubuntu/recommend_lambda"
          strip_components: 1 # ai/ 경로를 때어내고 파일들을 전송

      # 3. EC2 원격 접속 후 파이썬 가상환경 활성화 및 가동 스크립트 실행
      - name: Restart Python Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/recommend_lambda
            chmod +x deploy.sh
            ./deploy.sh
